### PR TITLE
Implemented EDD Subscriptions Endpoint

### PR DESCRIPTION
**Pull request by sulemaanhamza**

### CODE REVIEW

**Comment by sulemaanhamza** [comment]
@flowdee It's implemented. You have to update the WordPress plugin file as well.

image

**Comment by flowdee** [comment]
Technically, it works fine, thanks so far @sulemaanhamza .

But we should make sure that we align with the current layout and styles of the other EDD boxes.

Bildschirmfoto 2024-04-29 um 09 49 21

The boxes should have the same widths & paddings (1 + 2) like the ones above.

The position of the "tag" (3) for the status should be at the same position like the ones of the orders etc.

The gray bar at the bottom (4) should be re-used here as well, in the best case for the creation date, like the ones of the orders. Creation date is empty in my examples, btw (5).

Maybe you can start stealing the markup of the order, and then place our contents into. Propably makes it easier?

**Comment by sulemaanhamza** [comment]
> Technically, it works fine, thanks so far @sulemaanhamza .
> 
> But we should make sure that we align with the current layout and styles of the other EDD boxes.
> 
> Bildschirmfoto 2024-04-29 um 09 49 21
> 
> The boxes should have the same widths & paddings (1 + 2) like the ones above.
> 
> The position of the "tag" (3) for the status should be at the same position like the ones of the orders etc.
> 
> The gray bar at the bottom (4) should be re-used here as well, in the best case for the creation date, like the ones of the orders. Creation date is empty in my examples, btw (5).
> 
> Maybe you can start stealing the markup of the order, and then place our contents into. Propably makes it easier?

@flowdee I'm working on the design and now it's pretty much close to the orders one. Can you suggest any further changes? (screenshot)

image

**Comment by flowdee** [comment]
Looks fine to me! @sulemaanhamza

**Pull request merged**
